#!/usr/bin/env python3
"""Generate full-screen battery warnings (same LSB-left format as boot logo)."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'

def render(text):
    image = Image.new('1', (256, 128), 1)
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(FONT, 26)
    box = draw.textbbox((0, 0), text, font=font)
    draw.text(((256 - box[2]) // 2, (128 - box[3] - box[1]) // 2), text, font=font, fill=0)
    return image

def main():
    header = ['// Generated by scripts/render_battery_messages.py; 1 = white, LSB left.',
              '#pragma once', '#include <cstdint>', 'namespace esphome::gtag_display::battery_messages {']
    for name, text in [('LOW', 'Low battery'), ('ERROR', 'Battery error')]:
        image = render(text)
        data = [sum(image.getpixel((x + bit, y)) << bit for bit in range(8))
                for y in range(128) for x in range(0, 256, 8)]
        header.append(f'inline constexpr uint8_t {name}[4096] = {{')
        header.extend('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i+32]) + ',' for i in range(0, 4096, 32))
        header.append('};')
    header.append('}')
    (ROOT / 'config/esphome/components/gtag_display/battery_messages.h').write_text('\n'.join(header) + '\n')

if __name__ == '__main__':
    main()
