#!/usr/bin/env python3
"""Render the 1-bit startup screen and its ready-to-use firmware header.

Design-only dependencies: Pillow, qrcode==8.2, zxing-cpp==3.0.0.
The last dependency verifies the QR in the final 256x128 image.
"""

from pathlib import Path

import qrcode
from PIL import Image, ImageDraw, ImageFont
import zxingcpp


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "design"
HEADER = ROOT / "config/esphome/components/gtag_display/boot_logo.h"
FONT = ROOT / "custom_components" / "gtag_ble_test" / "fonts" / "DejaVuSans.ttf"
URL = "https://github.com/lukdut/gtag-nrf-display"
VISIBLE_URL = URL.removeprefix("https://")
SIZE = (256, 128)
TAG = ((2, 0), (38, 0), (54, 16), (54, 24), (38, 40), (2, 40), (0, 38), (0, 2))
LETTER_G = ("01110", "10001", "10000", "10111", "10001", "10001", "01110")


def make_mark() -> tuple[Image.Image, str]:
    """A price tag with a pixel G and a hole, on a 55x41 grid."""
    mark = Image.new("1", (55, 41), 1)
    draw = ImageDraw.Draw(mark)
    draw.polygon(TAG, fill=0)
    svg = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 55 41">',
        '  <title>GTag — electronic display tag</title>',
        '  <polygon points="' + " ".join(f"{x},{y}" for x, y in TAG) + '" fill="black"/>',
    ]
    for y, row in enumerate(LETTER_G):
        for x, pixel in enumerate(row):
            if pixel == "1":
                left, top = 10 + x * 3, 10 + y * 3
                draw.rectangle((left, top, left + 2, top + 2), fill=1)
                svg.append(f'  <rect x="{left}" y="{top}" width="3" height="3" fill="white"/>')
    draw.rectangle((42, 18, 46, 22), fill=1)
    svg.append('  <rect x="42" y="18" width="5" height="5" fill="white"/>')
    svg.append("</svg>\n")
    return mark, "\n".join(svg)


def center_text(draw: ImageDraw.ImageDraw, text: str, center: int, top: int,
                size: int, stroke: int = 0) -> None:
    font = ImageFont.truetype(str(FONT), size)
    draw.text((center, top), text, font=font, fill=0, anchor="mt", stroke_width=stroke)


def firmware_header(screen: Image.Image) -> str:
    # Pillow packs the leftmost pixel into bit 7; the LCD expects bit 0.
    reverse_bits = bytes(int(f"{value:08b}"[::-1], 2) for value in range(256))
    frame = screen.tobytes().translate(reverse_bits)
    assert len(frame) == 4096
    rows = ["    " + ", ".join(f"0x{value:02X}" for value in frame[i:i + 16]) + ","
            for i in range(0, len(frame), 16)]
    return "\n".join([
        "// Generated by scripts/render_boot_logo.py; do not edit by hand.",
        "// 256x128, row-major, leftmost pixel in bit 0; white = 1.",
        f"// QR destination: {URL}",
        "#pragma once", "", "#include <array>", "#include <cstdint>", "",
        "namespace esphome::gtag_display::boot_logo {", "",
        "inline constexpr std::array<uint8_t, 4096> FRAME{{", *rows, "}};", "",
        "}  // namespace esphome::gtag_display::boot_logo", "",
    ])


def main() -> None:
    qr = qrcode.QRCode(
        version=3, error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=3, border=4,
    )
    qr.add_data(URL, optimize=0)
    qr.make(fit=False)
    qr_image = qr.make_image(fill_color="black", back_color="white").get_image().convert("1")
    assert qr_image.size == (111, 111)

    mark, svg = make_mark()
    screen = Image.new("1", SIZE, 1)
    screen.paste(mark, (42, 8))
    screen.paste(qr_image, (141, 0))
    draw = ImageDraw.Draw(screen)
    center_text(draw, "GTag", 69, 55, 32, stroke=1)
    center_text(draw, "D I S P L A Y", 69, 94, 9)
    draw.line((10, 112, 245, 112), fill=0)
    # Keep rows 125..127 free for the on-device battery indicator.
    center_text(draw, VISIBLE_URL, 128, 115, 10)

    # Validate the composed screen, including neighbouring text and graphics.
    results = zxingcpp.read_barcodes(screen.convert("RGB"))
    assert len(results) == 1 and results[0].text == URL, results
    assert screen.mode == "1" and screen.size == SIZE

    OUT.mkdir(parents=True, exist_ok=True)
    screen.save(OUT / "boot-logo.png", optimize=True)
    screen.resize((1024, 512), Image.Resampling.NEAREST).save(OUT / "boot-logo-preview.png", optimize=True)
    (OUT / "gtag-mark.svg").write_text(svg, encoding="utf-8")
    HEADER.write_text(firmware_header(screen), encoding="utf-8")
    print(f"Saved startup images to {OUT} and firmware frame to {HEADER}")
    print(f"QR verified at native resolution: {results[0].text}")
    print("QR: version 3, error correction M, 3 pixels/module, quiet zone 4 modules")


if __name__ == "__main__":
    main()
